import type { Metadata } from "next";
import "./globals.css";

import localFont from "next/font/local";
import Opener from "./components/opener/Opener";

const invitacionFont = localFont({
  src: [
    {
      path: "../public/fonts/GreatVibes-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-invitacion",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={invitacionFont.variable}>
      <body className={``}>
        <Opener />
        {children}
      </body>
    </html>
  );
}
